with open(r"d:\dongho\www\style.css", "r", encoding="utf-8") as f:
    lines = f.readlines()

new_lines = lines[:629]
new_lines.append(".date-display.visible,\n")
new_lines.append(".lunar-display.visible {\n")
new_lines.append("    display: inline-block;\n")
new_lines.append("}\n\n")
new_lines.append(".lunar-display {\n")
new_lines.append("    color: #f59e0b;\n")
new_lines.append("    font-style: italic;\n")
new_lines.append("}\n\n")
new_lines.append("/* ====== Chế độ xếp dọc ====== */\n")
new_lines.append(".digits-display.vertical {\n")
new_lines.append("    display: grid;\n")
new_lines.append("    grid-template-columns: auto auto;\n")
new_lines.append("    justify-content: center;\n")
new_lines.append("    align-items: center;\n")
new_lines.append("    row-gap: 8px;\n")
new_lines.append("    column-gap: 3px;\n")
new_lines.append("}\n\n")
new_lines.append(".digits-display.vertical #wrap-h1 { grid-column: 1; grid-row: 1; }\n")
new_lines.append(".digits-display.vertical #wrap-h2 { grid-column: 2; grid-row: 1; }\n")
new_lines.append(".digits-display.vertical #wrap-colon1 { grid-column: 1 / span 2; grid-row: 2; justify-self: center; }\n")
new_lines.append(".digits-display.vertical #wrap-m1 { grid-column: 1; grid-row: 3; }\n")
new_lines.append(".digits-display.vertical #wrap-m2 { grid-column: 2; grid-row: 3; }\n")
new_lines.append(".digits-display.vertical #wrap-colon2 { grid-column: 1 / span 2; grid-row: 4; justify-self: center; }\n")
new_lines.append(".digits-display.vertical #wrap-s1 { grid-column: 1; grid-row: 5; }\n")
new_lines.append(".digits-display.vertical #wrap-s2 { grid-column: 2; grid-row: 5; }\n\n")
new_lines.append(".digits-display.vertical img.colon {\n")
new_lines.append("    height: var(--colon-size);\n")
new_lines.append("    width: auto;\n")
new_lines.append("    margin: calc(var(--colon-size) * (var(--colon-spacing, -12) / 100)) 0;\n")
new_lines.append("    transform: rotate(90deg);\n")
new_lines.append("}\n\n")
new_lines.append("/* ====== Drag Wrapper (Kéo thả phần tử) ====== */\n")
new_lines.append(".drag-wrapper {\n")
new_lines.append("    display: inline-block;\n")
new_lines.append("    position: relative;\n")
new_lines.append("    transition: transform 0.15s ease;\n")
new_lines.append("}\n\n")
new_lines.append(".editing-mode .drag-wrapper,\n")
new_lines.append(".editing-mode .date-display,\n")
new_lines.append(".editing-mode .week-display,\n")
new_lines.append(".editing-mode .lunar-display {\n")

new_lines.extend(lines[629:])

with open(r"d:\dongho\www\style.css", "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print("Fixed style.css")
